Implemented case structure
fabianschwamborn/HVAC-shark pull request #1
Opened 2024-11-09 12:52 UTC by FragHunter

2024-11-09 12:52 UTC, FragHunter commented
Hej ;)

2024-11-09 17:26 UTC, fabianschwamborn requested changes

2024-11-09 17:26 UTC, fabianschwamborn commented on dongle/mid_xye/software/decode_xye.cpp
> +      case MASTER_START_BYTE:
this does not fit: when the receiver is not in a state of receiving a frame (receivingRS485Sequence) then it should just take the byte and enter into sequence state. If the receiver is collecting bytes, then there are 3 cases

1.  received an end byte 
2. missed something and gets a start sequence
3. has buffer overflow 
in this 3 cases the buffer shall be printed (because of the receiving sequence)

2024-11-11 23:22 UTC, closed without merging

2024-11-11 23:23 UTC, fabianschwamborn commented
fixed the section directly but left the sequence start as it is.